### ISSUE TITLE
flutter_opencv_example has stopped

### ISSUE THREAD

**Issue by mohamadkenway** [westracer/flutter_native_opencv#3] opened 2020-12-09 11:49 UTC
when i run project it say flutter_opencv_example has stopped and cant running

**Comment by westracer** [comment] 2020-12-09 14:26
Hello. Have you added the OpenCV library to the app? If you haven't, please, check out the readme on how to do that.

If you added the library and it still doesn't work, I'm gonna need some more detailed info: which platform are you using, OpenCV version, exception callstack, etc.

**Comment by mohamadkenway** [comment] 2020-12-09 17:48
Hello Westracer 

When i run in debug mode on emulator its not working but when i buid release apk in install that it works !

i have this logs when i run in debug mode 

Launching lib\main.dart on Samsung A50 in debug mode...
Running Gradle task 'assembleDebug'...
E/FlutterLoader( 2333): Flutter initialization failed.
E/FlutterLoader( 2333): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/lib/x86, /data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader( 2333): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader( 2333): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader( 2333): 	at io.flutter.embedding.engine.f.a.a(Unknown Source:23)
E/FlutterLoader( 2333): 	at io.flutter.embedding.engine.a.<init>(Unknown Source:150)
E/FlutterLoader( 2333): 	at io.flutter.embedding.engine.a.<init>(Unknown Source:19)
E/FlutterLoader( 2333): 	at io.flutter.embedding.android.e.k(Unknown Source:110)
E/FlutterLoader( 2333): 	at io.flutter.embedding.android.e.a(Unknown Source:7)
E/FlutterLoader( 2333): 	at io.flutter.embedding.android.d.onCreate(Unknown Source:22)
E/FlutterLoader( 2333): 	at android.app.Activity.performCreate(Activity.java:7136)
E/FlutterLoader( 2333): 	at android.app.Activity.performCreate(Activity.java:7127)
E/FlutterLoader( 2333): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/FlutterLoader( 2333): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/FlutterLoader( 2333): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/FlutterLoader( 2333): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/FlutterLoader( 2333): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/FlutterLoader( 2333): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/FlutterLoader( 2333): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/FlutterLoader( 2333): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader( 2333): 	at android.os.Looper.loop(Looper.java:193)
E/FlutterLoader( 2333): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/FlutterLoader( 2333): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 2333): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/FlutterLoader( 2333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/FlutterLoader( 2333): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/lib/x86, /data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader( 2333): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
E/FlutterLoader( 2333): 	at java.lang.System.loadLibrary(System.java:1669)
E/FlutterLoader( 2333): 	at io.flutter.embedding.engine.f.a$a.call(Unknown Source:10)
E/FlutterLoader( 2333): 	at io.flutter.embedding.engine.f.a$a.call(Unknown Source:0)
E/FlutterLoader( 2333): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader( 2333): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader( 2333): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader( 2333): 	at java.lang.Thread.run(Thread.java:764)
Parameter format not correct -
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...

when it installed application cant run and show message flutter_opencv_example has stopped and log again



E/FlutterLoader( 2461): Flutter initialization failed.
E/FlutterLoader( 2461): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/lib/x86, /data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader( 2461): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader( 2461): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader( 2461): 	at io.flutter.embedding.engine.f.a.a(Unknown Source:23)
E/FlutterLoader( 2461): 	at io.flutter.embedding.engine.a.<init>(Unknown Source:150)
E/FlutterLoader( 2461): 	at io.flutter.embedding.engine.a.<init>(Unknown Source:19)
E/FlutterLoader( 2461): 	at io.flutter.embedding.android.e.k(Unknown Source:110)
E/FlutterLoader( 2461): 	at io.flutter.embedding.android.e.a(Unknown Source:7)
E/FlutterLoader( 2461): 	at io.flutter.embedding.android.d.onCreate(Unknown Source:22)
E/FlutterLoader( 2461): 	at android.app.Activity.performCreate(Activity.java:7136)
E/FlutterLoader( 2461): 	at android.app.Activity.performCreate(Activity.java:7127)
E/FlutterLoader( 2461): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/FlutterLoader( 2461): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/FlutterLoader( 2461): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/FlutterLoader( 2461): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/FlutterLoader( 2461): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/FlutterLoader( 2461): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/FlutterLoader( 2461): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/FlutterLoader( 2461): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader( 2461): 	at android.os.Looper.loop(Looper.java:193)
E/FlutterLoader( 2461): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/FlutterLoader( 2461): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 2461): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/FlutterLoader( 2461): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/FlutterLoader( 2461): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/lib/x86, /data/app/com.example.flutter_opencv_example-sLIKjw6bLboHBYcBVy5znQ==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader( 2461): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
E/FlutterLoader( 2461): 	at java.lang.System.loadLibrary(System.java:1669)
E/FlutterLoader( 2461): 	at io.flutter.embedding.engine.f.a$a.call(Unknown Source:10)
E/FlutterLoader( 2461): 	at io.flutter.embedding.engine.f.a$a.call(Unknown Source:0)
E/FlutterLoader( 2461): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader( 2461): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader( 2461): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader( 2461): 	at java.lang.Thread.run(Thread.java:764)

**Comment by westracer** [comment] 2021-10-31 08:16
Sorry, I couldn't reproduce the problem. Closing the issue - feel free to reopen if the problem still occurs

**Closed as completed by westracer** 2021-10-31 08:16 UTC
